// js/translate.js

window.translations = {
    ru: {
        // Навигация и общие элементы
        "nav-catalog": "Каталог",
        "nav-guarantees": "Гарантии",
        "nav-faq": "FAQ",
        "nav-subscription": "Подписка",
        "nav-contacts": "Контакты",
        "btn-auth": "Регистрация / Вход",
        "back-to-home": "На главную",
        "search-placeholder": "Поиск услуг...",
        "btn-details": "Подробнее",
        "btn-add": "Добавить",
        "btn-ok": "Хорошо",
        "btn-send": "Отправить",
        "btn-subscribe": "Оформить подписку",
        "btn-register": "Зарегистрироваться",
        "btn-login-link": "Войти",
        "btn-generate": "Сгенерировать",
        "btn-go-to-checkout": "Перейти к оформлению",
        "btn-order-service": "Заказать услугу",
        "hero-title": "Все услуги для вашего бизнеса в одном месте",
        "hero-desc": "Enterprise – универсальная «кнопка» для решения ваших повседневных задач. Делегируйте операционные моменты нам и сосредоточьтесь на собственном деле.",
        "hero-btn": "Попробуйте сейчас",
        "services-title": "Доступные услуги и подписки",
        "sort-default": "По умолчанию",
        "sort-az": "По названию (А-Я)",
        "sort-za": "По названию (Я-А)",
        "loading": "Загрузка услуг...",
        "nothing-found": "Ничего не найдено",
        "sub-title": "Подписки",
        "sub-legal": "Юридические услуги",
        "sub-legal-desc": "Набор всех юридических услуг со скидкой 15% при оплате за месяц",
        "sub-design": "Дизайнерские услуги",
        "sub-design-desc": "Набор услуг дизайна со скидкой 15% при оплате за месяц",
        "sub-marketplace": "Услуги для маркетплейсов",
        "sub-marketplace-desc": "Набор основных услуг для маркетплейсов со скидкой 15% при оплате за месяц",
        "btn-sub-details": "Подробнее о подписках",
        "process-title": "Как мы работаем?",
        "step-1-text": "Формирование технического задания и предоплата 50%",
        "step-2-text": "Сдача предварительного результата работ",
        "step-3-text": "Внесение корректировок и полная оплата заказа",
        "step-4-text": "Получение результата работ любым способом",
        "guarantees-title": "Гарантии",
        "g-1-title": "Не требуем 100% предоплаты",
        "g-1-desc": "Чтобы начать работу, достаточно заплатить 50% от оговоренной стоимости.",
        "g-2-title": "Дело доверено профессионалам",
        "g-2-desc": "Услуги реализовываются исключительно специалистами Enterprise.",
        "g-3-title": "Полный возврат",
        "g-3-desc": "Если результат услуги выйдет некачественным, мы вернем все деньги.",
        "g-4-title": "Гарантийный срок 2 недели",
        "g-4-desc": "Исправим любые возможные недоработки бесплатно.",
        "team-title": "Команда проекта Enterprise",
        "team-member-1-name": "Василий Буреев",
        "team-member-1-role": "основатель",
        "team-member-2-name": "Кирилл Чернаков",
        "team-member-2-role": "сооснователь",
        "team-member-3-name": "Даниил Иванов",
        "team-member-3-role": "разработчик",
        "team-member-4-name": "Иван Петров",
        "team-member-4-role": "менеджер",
        "team-principle": "Принципом работы нашей команды является честность, добросовестность, а главное – постоянный контроль качества оказываемых услуг и отзывчивость в решении любой задачи.",
        "reviews-title": "Отзывы постоянных клиентов",
        "review-1-name": "Кирилл М.",
        "review-1-role": "управляющий менеджер CreativeLab",
        "review-1-text": "Давно сотрудничаю с командой Enterprise, много раз выручали меня с различными операционными вопросами, в частности, полностью реализовали дизайн социальных сетей, сделали сайт и наладили работу с маркетплейсом OZON.",
        "review-2-name": "Александр Ж.",
        "review-2-role": "основатель NFT-проекта Quarter Aesthetics",
        "review-2-text": "Обращался к компании несколько раз: сначала требовалось оперативно сверстать сайт по моему макету, что было успешно реализовано, затем нужно было подготовить изображения под требования для печати по ткани. Работой я остался доволен.",
        "review-3-name": "Павел С.",
        "review-3-role": "совладелец магазина кроссовок Shirma Store",
        "review-3-text": "Спасибо большое, нужно было сделать дизайн страницы магазина кроссовок в Инстаграме и помочь в целом запустить проект. Моим вопросом занимался лично основатель и это было очень приятно.",
        "review-4-name": "Даниил М.",
        "review-4-role": "совладелец бренда одежды Resell Merch",
        "review-4-text": "Как только возникло желание создать собственный бренд одежды, сразу же решил обратиться к команде проекта и в итоге получил хороший дизайн соцсетей и скидку на пошив от партнеров, а также пару ценных советов по продвижению.",
        "faq-title": "FAQ",
        "q-1": "Как непосредственно будет проходить общение с командой проекта?",
        "a-1": "Общение происходит через удобный для вас мессенджер или по электронной почте.",
        "q-2": "Почему я должен(-на) обратиться к вам прямо сейчас?",
        "a-2": "Чем раньше вы начнете, тем быстрее получите результат.",
        "q-3": "Каким образом возможна оплата?",
        "a-3": "Мы принимаем оплату банковским переводом, картой и через электронные кошельки.",
        "contact-title": "Остались вопросы или есть предложения?",
        "contact-desc": "Напишите нам в официальные аккаунты в социальных сетях и мессенджерах или позвоните по телефону и наши сотрудники решат вашу проблему",
        "footer-legal-info": "Общая правовая информация",
        "footer-privacy": "Политика конфиденциальности",
        "footer-payments": "Политика платежей",
        "footer-investors": "Информация для инвесторов",
        "footer-portfolio": "Портфолио",
        "footer-resume": "Отправить свое резюме",
        "checkout-title": "Оформление заказа",
        "select-method": "Способ обсуждения",
        "by-phone": "По телефону",
        "by-email": "По почте",
        "confidentiality": "Информация конфиденциальна и не передается третьим лицам",
        "checkout-total": "Итого:",
        "success-order-title": "Ваш заказ успешно оформлен",
        "success-order-desc": "Наши менеджеры уже обрабатывают его. Скоро с вами свяжутся для обсуждения деталей.<br>Пожалуйста, в случае возникновения любых вопросов, свяжитесь с нами любым удобным способом:",
        "sub-modal-title": "Заявка на подключение подписки",
        "success-sub-title": "Ваша заявка на рассмотрении",
        "success-sub-desc": "Наши менеджеры уже обрабатывают ее. Скоро с вами свяжутся для обсуждения деталей.<br>Пожалуйста, в случае возникновения любых вопросов, свяжитесь с нами любым удобным способом:",
        "cart-empty-1": "Корзина пуста",
        "cart-empty-2": "",
        "service-label": "услуга",
        "price-request": "По запросу",
        "page-404-link": "Страница 404 (Тест)",
        "cart-added": "добавлен в корзину!",
        "reg-title": "Регистрация",
        "label-phone": "Телефон *",
        "placeholder-phone-reg": "+375 XX XXX-XX-XX",
        "label-email": "Email *",
        "placeholder-email-reg": "example@mail.com",
        "label-dob": "Дата рождения *",
        "label-fullname": "ФИО *",
        "placeholder-fullname-reg": "Иванов Иван Иванович",
        "label-nickname": "Никнейм *",
        "placeholder-nickname": "Придумайте или сгенерируйте",
        "label-password": "Пароль *",
        "placeholder-password-reg": "Мин. 8 символов, A-Z, a-z, 0-9, спецсимвол",
        "agree-text": "Я согласен с",
        "service-rules": "правилами сервиса",
        "have-account": "Уже есть аккаунт?",
        "hide-password": "Скрыть пароль",
        "show-password": "Показать пароль",
        "error-phone-format": "Формат: +375XXXXXXXXX (только цифры после кода)",
        "error-email-invalid": "Введите корректный email",
        "error-age-min": "Регистрация доступна только с 16 лет",
        "error-pass-requirements": "8-20 симв., A-Z, a-z, 0-9, @$!%*?&",
        "error-agree-required": "Необходимо принять правила сервиса",
        "error-nick-required": "Введите или сгенерируйте никнейм",
        "success-reg": "Регистрация успешна! Добро пожаловать, ",
        "error-server-exists": "Такой пользователь уже существует",
        "error-server-connect": "Не удалось подключиться к серверу. Убедитесь, что json-server запущен на порту 3000.",
        "cat-legal-title": "Юридические услуги",
        "legal-service-1-title": "Составление иска в суд",
        "legal-service-1-desc": "Юристы нашей команды созвонятся с вами по телефону, выслушают фабулу дела, зададут несколько наводящих вопросов и подготовят грамотный иск.",
        "legal-service-2-title": "Договор купли-продажи",
        "legal-service-2-desc": "Вы сможете поручить команде наших юристов составить профессиональный договор купли-продажи, в соответствии с нормами ГК РФ. В договор можно будет прописать дополнительные положения по запросу заказчика бесплатно.",
        "legal-service-3-title": "Договор аренды",
        "legal-service-3-desc": "Наши эксперты в сфере юриспруденции помогут вам составить профессиональный договор аренды помещений, предприятий, транспортных средств и иных в соответствии с ГК РФ. В процессе подготовки документа будут учтены все ваши пожелания.",
        "legal-service-4-title": "Договор подряда",
        "legal-service-4-desc": "Если вы хотите получить работу качественно и в срок – обратите внимание на договор подряда. Мы имеем многолетний опыт составления юридических документов и готовы подготовить договор в контексте конкретно вашей ситуации.",
        "legal-service-5-title": "Трудовой договор",
        "legal-service-5-desc": "Трудовые отношения – обширная отрасль права, разобраться в которой непросто. Наши специалисты регулярно консультируются с кадровиками и бухгалтерами по вопросам заключения трудовых договоров и готовы помочь с этим и вам.",
        "legal-service-6-title": "Юридическая консультация",
        "legal-service-6-desc": "В настоящее время юридические аспекты все больше и больше захватывают нашу жизнь, поэтому всегда важно иметь возможность юридической консультации. Один из наших юристов готов созвониться с вами в ближайшее время.",
        "time-from-2-days": "от 2 дней",
        "time-from-1-day": "от 1 дня",
        "price-from-4000": "от 4.000₽",
        "price-from-3000": "от 3.000₽",
        "cart-title": "Корзина",
        "contacts-modal-title": "Рады будем ответить на ваши вопросы",
        "contacts-modal-desc": "Напишите нам в наши мессенджеры, электронную почту, в официальные аккаунты в социальных сетях или позвоните по телефону:",
        "placeholder-fullname": "Фамилия и имя",
        "placeholder-phone": "Номер телефона",
        "placeholder-email": "Электронная почта",
        "placeholder-comment": "Комментарий",
        "cat-it-title": "IT-услуги",
        "page-title-it": "Enterprise - IT-услуги",
        "it-service-1-title": "Верстка HTML / CSS / JS",
        "it-service-1-desc": "Если у вас есть макет, по которому необходимо сверстать одну или несколько веб-страниц, отправьте его на оценку нашей команде.",
        "it-service-2-title": "Создание чат-бота VK / Telegram",
        "it-service-2-desc": "Чат-бот является отличным функциональным и маркетинговым инструментом.",
        "it-service-3-title": "Создание скрипта JavaScript",
        "it-service-3-desc": "Скрипт на JS может решать задачи абсолютно разного плана.",
        "it-service-4-title": "SEO-оптимизация",
        "it-service-4-desc": "Один из самых дешевых и действенных методов продвижения.",
        "time-from-3-days": "от 3 дней",
        "price-from-1000": "от 1.000₽",
        "price-from-2000": "от 2.000₽",
        "vision-font-size": "Размер шрифта:",
        "vision-color-scheme": "Цветовая схема:",
        "vision-bw": "Ч/Б",
        "vision-wb": "Б/Ч",
        "vision-blue": "Синяя",
        "vision-images": "Вкл/Выкл изображения",
        "vision-reset": "Обычная версия",
        "cat-design-title": "Услуги дизайна",
        "page-title-design": "Enterprise - Услуги дизайна",
        "design-service-1-title": "Дизайн логотипа",
        "design-service-1-desc": "Создадим уникальный логотип, который выделит ваш бренд среди конкурентов.",
        "design-service-2-title": "Дизайн сайта (UI/UX)",
        "design-service-2-desc": "Проработаем удобный и современный интерфейс для вашего веб-ресурса.",
        "time-from-7-days": "от 7 дней",
        "price-from-5000": "от 5.000₽",
        "price-from-15000": "от 15.000₽",
        "cat-marketing-title": "Маркетинг",
        "page-title-marketing": "Enterprise - Маркетинг",
        "marketing-service-1-title": "Ведение соцсетей (SMM)",
        "marketing-service-1-desc": "Полное ведение ваших аккаунтов: контент-план, посты, сторис и работа с аудиторией.",
        "marketing-service-2-title": "Настройка таргетированной рекламы",
        "marketing-service-2-desc": "Найдем вашу целевую аудиторию и запустим эффективные рекламные кампании.",
        "time-monthly": "ежемесячно",
        "time-from-5-days": "от 5 дней",
        "price-from-20000": "от 20.000₽",
        "price-from-10000": "от 10.000₽",
        "cat-hr-title": "Кадровые услуги",
        "page-title-hr": "Enterprise - Кадровые услуги",
        "hr-service-1-title": "Подбор персонала",
        "hr-service-1-desc": "Найдем лучших специалистов под ваши задачи: от линейного персонала до топ-менеджеров.",
        "hr-service-2-title": "Кадровое делопроизводство",
        "hr-service-2-desc": "Оформление трудовых договоров, приказов, личных карточек и другой кадровой документации.",
        "time-from-10-days": "от 10 дней",
        "time-on-request": "по запросу",
        "price-from-30000": "от 30.000₽",
        "cat-ecommerce-title": "Для маркетплейсов",
        "page-title-ecommerce": "Enterprise - Для маркетплейсов",
        "ecommerce-service-1-title": "Выход на Wildberries",
        "ecommerce-service-1-desc": "Поможем зарегистрироваться, оформить карточки товаров и запустить первые продажи на WB.",
        "ecommerce-service-2-title": "Продвижение на Ozon",
        "ecommerce-service-2-desc": "SEO-оптимизация карточек, настройка рекламы и аналитика продаж на маркетплейсе Ozon.",
        "time-from-14-days": "от 14 дней",
        "price-from-25000": "от 25.000₽",
        "page-title-sub": "Enterprise - Подписки",
        "btn-back": "← Вернуться назад",
        "sub-hero-title": "Подписка – возможность делегировать задачи",
        "sub-hero-desc": "Enterprise – это хорошо. Но еще лучше может быть только подписка, поскольку она предоставляет все те же услуги, но со скидкой 15% при оплате за месяц.",
        "sub-benefits-title": "Преимущества работы по подписке",
        "benefit-1": "На 15% дешевле, чем если брать по отдельности",
        "benefit-2": "К каждому подписчику прикреплен личный менеджер",
        "benefit-3": "Индивидуальный подход к вашему проекту",
        "benefit-4": "Экономите время, не тратя его на повторные обращения",
        "benefit-5": "Все самое нужное уже внутри подписки",
        "available-plans-title": "Доступные подписки",
        "plan-design-label": "Услуги дизайна",
        "plan-design-desc": "Набор услуг подбирается индивидуально в зависимости от потребности клиента",
        "price-individual": "индивидуально",
        "plan-marketplace-label": "Для маркетплейсов",
        "plan-marketplace-desc": "Запуск и ведение магазина<br>Неограниченные консультации",
        "price-marketplace": "20000р/мес",
        "plan-legal-label": "Юридические услуги",
        "plan-legal-desc": "Два любых договора<br>Две юридические консультации",
        "price-legal": "12000р/мес",
        "sub-checkbox-legal": "Юридические услуги (12000р/мес)",
        "sub-checkbox-design": "Услуги дизайна (12000р/мес)",
        "sub-checkbox-marketplace": "Услуги для маркетплейсов (20000р/мес)",
        "option-by-phone": "По телефону",
        "option-by-email": "По электронной почте",
        "desc-design-full": "Набор услуг подбирается индивидуально в зависимости от потребности клиента. В подписку могут входить: разработка логотипа, дизайн сайта, создание баннеров, оформление соцсетей и другие задачи. Стоимость рассчитывается после обсуждения ваших потребностей с менеджером.",
        "desc-marketplace-full": "Полный комплекс услуг для работы на маркетплейсах: запуск и ведение магазина на Wildberries, Ozon и других площадках. Неограниченные консультации по оптимизации карточек товаров, настройке рекламы и аналитике продаж. Персональный менеджер поможет увеличить ваши продажи.",
        "desc-legal-full": "Два любых договора на выбор (купли-продажи, аренды, подряда, трудовой и др.) с учетом всех ваших пожеланий. Две юридические консультации по любым вопросам: от проверки контрагентов до защиты прав потребителей. Все документы составляются в соответствии с актуальным законодательством РФ.",
         // Ключи для Legal Page
        "page-title-legal": "Политика конфиденциальности - Enterprise",
        "privacy-title": "Политика конфиденциальности",
        "privacy-intro": "Настоящая Политика конфиденциальности описывает, как компания «Enterprise» собирает, использует и защищает вашу личную информацию при использовании нашего веб-сайта и услуг.",
        "privacy-section-1-title": "1. Сбор информации",
        "privacy-section-1-text": "Мы можем собирать следующие типы информации:",
        "privacy-list-1": "Личные данные: имя, адрес электронной почты, номер телефона.",
        "privacy-list-2": "Технические данные: IP-адрес, тип браузера, операционная система.",
        "privacy-list-3": "Данные об использовании: страницы, которые вы посещаете, время пребывания на сайте.",
        "privacy-section-2-title": "2. Использование информации",
        "privacy-section-2-text": "Собранная информация используется для:",
        "privacy-use-1": "Предоставления и улучшения наших услуг.",
        "privacy-use-2": "Общения с вами по поводу ваших заказов или запросов.",
        "privacy-use-3": "Анализа работы сайта и выявления технических проблем.",
        "privacy-section-3-title": "3. Защита данных",
        "privacy-section-3-text": "Мы принимаем разумные меры безопасности для защиты вашей информации от несанкционированного доступа, изменения или уничтожения. Однако ни один метод передачи данных через Интернет не является на 100% безопасным.",
        "privacy-section-4-title": "4. Передача третьим лицам",
        "privacy-section-4-text": "Мы не продаем и не передаем вашу личную информацию третьим лицам, за исключением случаев, когда это требуется по закону или необходимо для выполнения ваших заказов (например, платежным системам).",
        "privacy-section-5-title": "5. Ваши права",
        "privacy-section-5-text": "Вы имеете право запросить доступ к вашим личным данным, их исправление или удаление. Для этого свяжитесь с нами по адресу info@enterpriseapp.ru.",
        "btn-back-home": "Вернуться на главную",

       // Обновленные ключи для 404
        "page-title-404": "Страница не найдена - Enterprise",
        "error-404-title": "Страница<br>не найдена :(",
        "error-404-desc": "Запрашиваемая страница не существует или еще не создана. Если вам необходимы услуги из нашего ассортимента, пожалуйста, выберите их из каталога.",
        "btn-back-home": "Вернуться на главную",

          // Ключи для Legal Page (обновленные)
        "page-title-legal": "Политика конфиденциальности - Enterprise",
        "privacy-title": "Общая правовая информация", // <-- Изменено
        "privacy-intro": "Настоящая Политика конфиденциальности описывает, как компания «Enterprise» собирает, использует и защищает вашу личную информацию при использовании нашего веб-сайта и услуг.",
        "privacy-section-1-title": "1. Сбор информации",
        "privacy-section-1-text": "Мы можем собирать следующие типы информации:",
        "privacy-list-1": "Личные данные: имя, адрес электронной почты, номер телефона.",
        "privacy-list-2": "Технические данные: IP-адрес, тип браузера, операционная система.",
        "privacy-list-3": "Данные об использовании: страницы, которые вы посещаете, время пребывания на сайте.",
        "privacy-section-2-title": "2. Использование информации",
        "privacy-section-2-text": "Собранная информация используется для:",
        "privacy-use-1": "Предоставления и улучшения наших услуг.",
        "privacy-use-2": "Общения с вами по поводу ваших заказов или запросов.",
        "privacy-use-3": "Анализа работы сайта и выявления технических проблем.",
        "privacy-section-3-title": "3. Защита данных",
        "privacy-section-3-text": "Мы принимаем разумные меры безопасности для защиты вашей информации от несанкционированного доступа, изменения или уничтожения. Однако ни один метод передачи данных через Интернет не является на 100% безопасным.",
        "privacy-section-4-title": "4. Передача третьим лицам",
        "privacy-section-4-text": "Мы не продаем и не передаем вашу личную информацию третьим лицам, за исключением случаев, когда это требуется по закону или необходимо для выполнения ваших заказов (например, платежным системам).",
        "privacy-section-5-title": "5. Ваши права",
        "privacy-section-5-text": "Вы имеете право запросить доступ к вашим личным данным, их исправление или удаление. Для этого свяжитесь с нами по адресу info@enterpriseapp.ru.",
         "btn-home": "На главную",
         'lk-title': 'Личный кабинет',
        'lk-my-data': 'Мои данные',
        'lk-my-orders': 'Мои заказы',
        'lk-nick': 'Никнейм',
        'lk-fio': 'ФИО',
        'lk-phone': 'Телефон',
        'lk-role': 'Роль',
        'lk-empty-cart': 'Ваша корзина пуста',
        'lk-total': 'Итого:',
         'page-title-admin': 'Админ-панель - Enterprise',
        'admin-title': 'Управление услугами',
        'admin-add-service': 'Добавить новую услугу (подпункт)',
        'admin-list': 'Список всех услуг по категориям',
        'btn-add-service': 'Добавить услугу',
        'cat-legal': 'Юридические',
        'cat-it': 'IT-услуги',
        'cat-design': 'Дизайн',
        'cat-marketing': 'Маркетинг',
        'cat-hr': 'HR',
        'cat-ecommerce': 'E-commerce',
        'placeholder-service-name': 'Название услуги',
        'placeholder-price': 'Цена (₽)',
        'placeholder-time': 'Срок (например, от 2 дней)',
        'placeholder-desc': 'Описание услуги',
        'placeholder-image': 'URL картинки (необязательно)',
        'btn-delete': 'Удалить',
        'nav-home': 'На главную',
        'btn-logout': 'Выйти',
        'btn-admin': 'Админ-панель',
        'btn-profile': 'Личный кабинет',

    },
    en: {
        // Navigation & Common
        "nav-catalog": "Catalog",
        "nav-guarantees": "Guarantees",
        "nav-faq": "FAQ",
        "nav-subscription": "Subscription",
        "nav-contacts": "Contacts",
        "btn-auth": "Register / Login",
        "back-to-home": "Home",
        "search-placeholder": "Search services...",
        "btn-details": "Details",
        "btn-add": "Add",
        "btn-ok": "OK",
        "btn-send": "Send",
        "btn-subscribe": "Subscribe Now",
        "btn-register": "Register",
        "btn-login-link": "Log in",
        "btn-generate": "Generate",
        "btn-go-to-checkout": "Proceed to Checkout",
        "btn-order-service": "Order Service",
        "hero-title": "All services for your business in one place",
        "hero-desc": "Enterprise is a universal 'button' for solving your daily tasks. Delegate operational moments to us and focus on your own business.",
        "hero-btn": "Try it now",
        "services-title": "Available services and subscriptions",
        "sort-default": "Default",
        "sort-az": "By name (A-Z)",
        "sort-za": "By name (Z-A)",
        "loading": "Loading services...",
        "nothing-found": "Nothing found",
        "sub-title": "Subscriptions",
        "sub-legal": "Legal services",
        "sub-legal-desc": "Set of all legal services with 15% discount for monthly payment",
        "sub-design": "Design services",
        "sub-design-desc": "Set of design services with 15% discount for monthly payment",
        "sub-marketplace": "Marketplace services",
        "sub-marketplace-desc": "Set of basic marketplace services with 15% discount for monthly payment",
        "btn-sub-details": "More about subscriptions",
        "process-title": "How we work?",
        "step-1-text": "Technical specification formation and 50% prepayment",
        "step-2-text": "Submission of preliminary results",
        "step-3-text": "Making adjustments and full payment",
        "step-4-text": "Receiving the result in any convenient way",
        "guarantees-title": "Guarantees",
        "g-1-title": "We don't require 100% prepayment",
        "g-1-desc": "To start working, it is enough to pay 50% of the agreed cost.",
        "g-2-title": "The case is entrusted to professionals",
        "g-2-desc": "Services are implemented exclusively by Enterprise specialists.",
        "g-3-title": "Full refund",
        "g-3-desc": "If the service result is of poor quality, we will return all money.",
        "g-4-title": "2-week warranty period",
        "g-4-desc": "We will fix any possible flaws for free.",
        "team-title": "Enterprise Project Team",
        "team-member-1-name": "Vasily Bureev",
        "team-member-1-role": "founder",
        "team-member-2-name": "Kirill Chernakov",
        "team-member-2-role": "co-founder",
        "team-member-3-name": "Daniil Ivanov",
        "team-member-3-role": "developer",
        "team-member-4-name": "Ivan Petrov",
        "team-member-4-role": "manager",
        "team-principle": "The principle of our team's work is honesty, conscientiousness, and most importantly - constant quality control of services provided and responsiveness in solving any task.",
        "reviews-title": "Reviews from regular clients",
        "review-1-name": "Kirill M.",
        "review-1-role": "managing manager of CreativeLab",
        "review-1-text": "I have been cooperating with the Enterprise team for a long time, they have helped me many times with various operational issues, in particular, they fully implemented the design of social networks, made a website and established work with the OZON marketplace.",
        "review-2-name": "Alexander Zh.",
        "review-2-role": "founder of NFT project Quarter Aesthetics",
        "review-2-text": "I contacted the company several times: first it was required to quickly layout a website according to my mockup, which was successfully implemented, then it was necessary to prepare images for fabric printing requirements. I was satisfied with the work.",
        "review-3-name": "Pavel S.",
        "review-3-role": "co-owner of Shirma Store sneaker shop",
        "review-3-text": "Thank you very much, I needed to make a design for the sneaker store page on Instagram and help launch the project in general. The founder personally handled my issue and it was very pleasant.",
        "review-4-name": "Daniil M.",
        "review-4-role": "co-owner of Resell Merch clothing brand",
        "review-4-text": "As soon as I wanted to create my own clothing brand, I immediately decided to contact the project team and ended up getting a good social media design and a discount on sewing from partners, as well as a couple of valuable promotion tips.",
        "faq-title": "FAQ",
        "q-1": "How will communication with the project team take place?",
        "a-1": "Communication takes place through a messenger convenient for you or by email.",
        "q-2": "Why should I contact you right now?",
        "a-2": "The sooner you start, the faster you get the result.",
        "q-3": "How is payment possible?",
        "a-3": "We accept payment by bank transfer, card and through electronic wallets.",
        "contact-title": "Any questions or suggestions?",
        "contact-desc": "Write to us in official accounts in social networks and messengers or call by phone and our employees will solve your problem",
        "footer-legal-info": "General legal information",
        "footer-privacy": "Privacy Policy",
        "footer-payments": "Payment Policy",
        "footer-investors": "Information for investors",
        "footer-portfolio": "Portfolio",
        "footer-resume": "Send your resume",
        "checkout-title": "Order checkout",
        "select-method": "Discussion method",
        "by-phone": "By phone",
        "by-email": "By email",
        "confidentiality": "Information is confidential and not shared with third parties",
        "checkout-total": "Total:",
        "success-order-title": "Your order has been successfully placed",
        "success-order-desc": "Our managers are already processing it. They will contact you soon to discuss details.<br>Please, if you have any questions, contact us in any convenient way:",
        "sub-modal-title": "Subscription connection request",
        "success-sub-title": "Your request is under review",
        "success-sub-desc": "Our managers are already processing it. They will contact you soon to discuss details.<br>Please, if you have any questions, contact us in any convenient way:",
        "cart-empty-1": "Cart is empty",
        "cart-empty-2": "",
        "service-label": "service",
        "price-request": "On request",
        "page-404-link": "404 Page (Test)",
        "cart-added": "added to cart!",
        "reg-title": "Registration",
        "label-phone": "Phone *",
        "placeholder-phone-reg": "+375 XX XXX-XX-XX",
        "label-email": "Email *",
        "placeholder-email-reg": "example@mail.com",
        "label-dob": "Date of Birth *",
        "label-fullname": "Full Name *",
        "placeholder-fullname-reg": "John Doe",
        "label-nickname": "Nickname *",
        "placeholder-nickname": "Create or generate",
        "label-password": "Password *",
        "placeholder-password-reg": "Min. 8 chars, A-Z, a-z, 0-9, special char",
        "agree-text": "I agree with the",
        "service-rules": "service rules",
        "have-account": "Already have an account?",
        "hide-password": "Hide password",
        "show-password": "Show password",
        "error-phone-format": "Format: +375XXXXXXXXX (digits only after code)",
        "error-email-invalid": "Please enter a valid email",
        "error-age-min": "Registration is available from 16 years old",
        "error-pass-requirements": "8-20 chars, A-Z, a-z, 0-9, @$!%*?&",
        "error-agree-required": "You must accept the service rules",
        "error-nick-required": "Enter or generate a nickname",
        "success-reg": "Registration successful! Welcome, ",
        "error-server-exists": "Such a user already exists",
        "error-server-connect": "Failed to connect to server. Make sure json-server is running on port 3000.",
        "cat-legal-title": "Legal Services",
        "legal-service-1-title": "Drafting a Lawsuit",
        "legal-service-1-desc": "Our team of lawyers will call you, listen to the facts of the case, ask a few leading questions and prepare a competent lawsuit.",
        "legal-service-2-title": "Sales Contract",
        "legal-service-2-desc": "You can entrust our team of lawyers to draw up a professional sales contract in accordance with the Civil Code of the Russian Federation. Additional provisions can be added to the contract at the customer's request free of charge.",
        "legal-service-3-title": "Lease Agreement",
        "legal-service-3-desc": "Our experts in the field of jurisprudence will help you draw up a professional lease agreement for premises, enterprises, vehicles and others in accordance with the Civil Code. All your wishes will be taken into account during the preparation of the document.",
        "legal-service-4-title": "Contracting Agreement",
        "legal-service-4-desc": "If you want to get the job done qualitatively and on time - pay attention to the contracting agreement. We have many years of experience in drafting legal documents and are ready to prepare a contract in the context of your specific situation.",
        "legal-service-5-title": "Employment Contract",
        "legal-service-5-desc": "Labor relations are a broad branch of law that is not easy to understand. Our specialists regularly consult with HR managers and accountants on issues of concluding employment contracts and are ready to help you with this as well.",
        "legal-service-6-title": "Legal Consultation",
        "legal-service-6-desc": "Currently, legal aspects are more and more capturing our lives, so it is always important to have the opportunity for legal consultation. One of our lawyers is ready to call you in the near future.",
        "time-from-2-days": "from 2 days",
        "time-from-1-day": "from 1 day",
        "price-from-4000": "from 4,000₽",
        "price-from-3000": "from 3,000₽",
        "cart-title": "Cart",
        "contacts-modal-title": "We will be happy to answer your questions",
        "contacts-modal-desc": "Write to us in our messengers, email, official accounts on social networks or call by phone:",
        "placeholder-fullname": "Full Name",
        "placeholder-phone": "Phone Number",
        "placeholder-email": "Email Address",
        "placeholder-comment": "Comment",
        "cat-it-title": "IT Services",
        "page-title-it": "Enterprise - IT Services",
        "it-service-1-title": "HTML / CSS / JS Layout",
        "it-service-1-desc": "If you have a mockup that needs to be laid out into one or more web pages, send it to our team for evaluation.",
        "it-service-2-title": "VK / Telegram Chatbot Creation",
        "it-service-2-desc": "A chatbot is an excellent functional and marketing tool.",
        "it-service-3-title": "JavaScript Script Creation",
        "it-service-3-desc": "A JS script can solve tasks of absolutely different plans.",
        "it-service-4-title": "SEO Optimization",
        "it-service-4-desc": "One of the cheapest and most effective promotion methods.",
        "time-from-3-days": "from 3 days",
        "price-from-1000": "from 1,000₽",
        "price-from-2000": "from 2,000₽",
        "vision-font-size": "Font Size:",
        "vision-color-scheme": "Color Scheme:",
        "vision-bw": "B/W",
        "vision-wb": "W/B",
        "vision-blue": "Blue",
        "vision-images": "Toggle Images",
        "vision-reset": "Normal Version",
        "cat-design-title": "Design Services",
        "page-title-design": "Enterprise - Design Services",
        "design-service-1-title": "Logo Design",
        "design-service-1-desc": "We will create a unique logo that will make your brand stand out from competitors.",
        "design-service-2-title": "Website Design (UI/UX)",
        "design-service-2-desc": "We will develop a convenient and modern interface for your web resource.",
        "time-from-7-days": "from 7 days",
        "price-from-5000": "from 5,000₽",
        "price-from-15000": "from 15,000₽",
        "cat-marketing-title": "Marketing",
        "page-title-marketing": "Enterprise - Marketing",
        "marketing-service-1-title": "Social Media Management (SMM)",
        "marketing-service-1-desc": "Full management of your accounts: content plan, posts, stories and audience engagement.",
        "marketing-service-2-title": "Targeted Advertising Setup",
        "marketing-service-2-desc": "We will find your target audience and launch effective advertising campaigns.",
        "time-monthly": "monthly",
        "time-from-5-days": "from 5 days",
        "price-from-20000": "from 20,000₽",
        "price-from-10000": "from 10,000₽",
        "cat-hr-title": "HR Services",
        "page-title-hr": "Enterprise - HR Services",
        "hr-service-1-title": "Personnel Recruitment",
        "hr-service-1-desc": "We will find the best specialists for your tasks: from line staff to top managers.",
        "hr-service-2-title": "HR Administration",
        "hr-service-2-desc": "Preparation of employment contracts, orders, personal cards and other HR documentation.",
        "time-from-10-days": "from 10 days",
        "time-on-request": "on request",
        "price-from-30000": "from 30,000₽",
        "cat-ecommerce-title": "For Marketplaces",
        "page-title-ecommerce": "Enterprise - For Marketplaces",
        "ecommerce-service-1-title": "Launching on Wildberries",
        "ecommerce-service-1-desc": "We will help you register, create product cards and launch your first sales on WB.",
        "ecommerce-service-2-title": "Promotion on Ozon",
        "ecommerce-service-2-desc": "SEO optimization of product cards, advertising setup and sales analytics on the Ozon marketplace.",
        "time-from-14-days": "from 14 days",
        "price-from-25000": "from 25,000₽",
        "page-title-sub": "Enterprise - Subscriptions",
        "btn-back": "← Go Back",
        "sub-hero-title": "Subscription – the ability to delegate tasks",
        "sub-hero-desc": "Enterprise is good. But a subscription can be even better, as it provides all the same services but with a 15% discount for monthly payment.",
        "sub-benefits-title": "Benefits of working by subscription",
        "benefit-1": "15% cheaper than buying separately",
        "benefit-2": "Each subscriber has a personal manager",
        "benefit-3": "Individual approach to your project",
        "benefit-4": "Save time by not spending it on repeated requests",
        "benefit-5": "Everything you need is already inside the subscription",
        "available-plans-title": "Available Subscriptions",
        "plan-design-label": "Design Services",
        "plan-design-desc": "The set of services is selected individually depending on the client's needs",
        "price-individual": "individual",
        "plan-marketplace-label": "For Marketplaces",
        "plan-marketplace-desc": "Launch and management of the store<br>Unlimited consultations",
        "price-marketplace": "20,000₽/month",
        "plan-legal-label": "Legal Services",
        "plan-legal-desc": "Two any contracts<br>Two legal consultations",
        "price-legal": "12,000₽/month",
        "sub-checkbox-legal": "Legal Services (12,000₽/month)",
        "sub-checkbox-design": "Design Services (12,000₽/month)",
        "sub-checkbox-marketplace": "Marketplace Services (20,000₽/month)",
        "option-by-phone": "By Phone",
        "option-by-email": "By Email",
        "desc-design-full": "The set of services is selected individually depending on the client's needs. The subscription may include: logo development, website design, banner creation, social media design, and other tasks. The cost is calculated after discussing your needs with the manager.",
        "desc-marketplace-full": "Full range of services for working on marketplaces: launching and managing a store on Wildberries, Ozon, and other platforms. Unlimited consultations on product card optimization, advertising setup, and sales analytics. A personal manager will help increase your sales.",
        "desc-legal-full": "Two contracts of your choice (sales, lease, contract, employment, etc.) taking into account all your wishes. Two legal consultations on any issues: from counterparty verification to consumer protection. All documents are drawn up in accordance with current legislation of the Russian Federation.",
          // Keys for Legal Page
        "page-title-legal": "Privacy Policy - Enterprise",
        "privacy-title": "Privacy Policy",
        "privacy-intro": "This Privacy Policy describes how Enterprise collects, uses, and protects your personal information when using our website and services.",
        "privacy-section-1-title": "1. Information Collection",
        "privacy-section-1-text": "We may collect the following types of information:",
        "privacy-list-1": "Personal data: name, email address, phone number.",
        "privacy-list-2": "Technical data: IP address, browser type, operating system.",
        "privacy-list-3": "Usage data: pages you visit, time spent on the site.",
        "privacy-section-2-title": "2. Use of Information",
        "privacy-section-2-text": "The collected information is used for:",
        "privacy-use-1": "Providing and improving our services.",
        "privacy-use-2": "Communicating with you regarding your orders or requests.",
        "privacy-use-3": "Analyzing site performance and identifying technical issues.",
        "privacy-section-3-title": "3. Data Protection",
        "privacy-section-3-text": "We take reasonable security measures to protect your information from unauthorized access, alteration, or destruction. However, no method of transmission over the Internet is 100% secure.",
        "privacy-section-4-title": "4. Third-Party Disclosure",
        "privacy-section-4-text": "We do not sell or transfer your personal information to third parties, except as required by law or necessary to fulfill your orders (e.g., payment processors).",
        "privacy-section-5-title": "5. Your Rights",
        "privacy-section-5-text": "You have the right to request access to, correction of, or deletion of your personal data. To do so, please contact us at info@enterpriseapp.ru.",
        "btn-back-home": "Back to Home",

        // Updated keys for 404
        "page-title-404": "Page Not Found - Enterprise",
        "error-404-title": "Page<br>Not Found :(",
        "error-404-desc": "The requested page does not exist or has not been created yet. If you need services from our assortment, please select them from the catalog.",
        "btn-back-home": "Back to Home",

          // Keys for Legal Page (updated)
        "page-title-legal": "Privacy Policy - Enterprise",
        "privacy-title": "General Legal Information", // <-- Changed
        "privacy-intro": "This Privacy Policy describes how Enterprise collects, uses, and protects your personal information when using our website and services.",
        "privacy-section-1-title": "1. Information Collection",
        "privacy-section-1-text": "We may collect the following types of information:",
        "privacy-list-1": "Personal data: name, email address, phone number.",
        "privacy-list-2": "Technical data: IP address, browser type, operating system.",
        "privacy-list-3": "Usage data: pages you visit, time spent on the site.",
        "privacy-section-2-title": "2. Use of Information",
        "privacy-section-2-text": "The collected information is used for:",
        "privacy-use-1": "Providing and improving our services.",
        "privacy-use-2": "Communicating with you regarding your orders or requests.",
        "privacy-use-3": "Analyzing site performance and identifying technical issues.",
        "privacy-section-3-title": "3. Data Protection",
        "privacy-section-3-text": "We take reasonable security measures to protect your information from unauthorized access, alteration, or destruction. However, no method of transmission over the Internet is 100% secure.",
        "privacy-section-4-title": "4. Third-Party Disclosure",
        "privacy-section-4-text": "We do not sell or transfer your personal information to third parties, except as required by law or necessary to fulfill your orders (e.g., payment processors).",
        "privacy-section-5-title": "5. Your Rights",
        "privacy-section-5-text": "You have the right to request access to, correction of, or deletion of your personal data. To do so, please contact us at info@enterpriseapp.ru.",
        "btn-home": "Home",
         'lk-title': 'Personal Account',
        'lk-my-data': 'My Data',
        'lk-my-orders': 'My Orders',
        'lk-nick': 'Nickname',
        'lk-fio': 'Full Name',
        'lk-phone': 'Phone',
        'lk-role': 'Role',
        'lk-empty-cart': 'Your cart is empty',
        'lk-total': 'Total:',
         'page-title-admin': 'Admin Panel - Enterprise',
        'admin-title': 'Service Management',
        'admin-add-service': 'Add New Service (Sub-item)',
        'admin-list': 'List of all services by category',
        'btn-add-service': 'Add Service',
        'cat-legal': 'Legal',
        'cat-it': 'IT Services',
        'cat-design': 'Design',
        'cat-marketing': 'Marketing',
        'cat-hr': 'HR',
        'cat-ecommerce': 'E-commerce',
        'placeholder-service-name': 'Service Name',
        'placeholder-price': 'Price (₽)',
        'placeholder-time': 'Time (e.g., from 2 days)',
        'placeholder-desc': 'Service Description',
        'placeholder-image': 'Image URL (optional)',
        'btn-delete': 'Delete',
        'nav-home': 'Home',
        'btn-logout': 'Logout',
        'btn-admin': 'Admin Panel',
        'btn-profile': 'Personal Account',
    
    }
};

function applyLanguage(lang) {
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    
    const langToggle = document.getElementById('lang-toggle');
    if (langToggle) langToggle.textContent = lang === 'ru' ? 'EN' : 'RU';

    // Обновляем обычный текст
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (window.translations[lang] && window.translations[lang][key]) {
            // Для FAQ вопросов сохраняем иконку плюса
            if (el.classList.contains('faq-question')) {
                const icon = el.querySelector('.faq-icon');
                el.innerHTML = window.translations[lang][key];
                if (icon) el.appendChild(icon); // Возвращаем иконку
            } else {
                el.innerHTML = window.translations[lang][key];
            }
        }
    });

    // Обновляем плейсхолдеры
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (window.translations[lang] && window.translations[lang][key]) {
            el.placeholder = window.translations[lang][key];
        }
    });

    // Перерисовываем услуги на главной
    if (typeof allServices !== 'undefined' && allServices.length > 0 && typeof renderServices === 'function') {
        const searchInput = document.getElementById('search-input');
        const query = searchInput ? searchInput.value.toLowerCase() : '';
        
        let filtered = allServices.filter(s => {
            const title = lang === 'en' ? (s.title_en || s.title) : s.title;
            const desc = lang === 'en' ? (s.description_en || s.description) : s.description;
            return title.toLowerCase().includes(query) || desc.toLowerCase().includes(query);
        });

        const sortSelect = document.getElementById('sort-select');
        if (sortSelect) {
            const sortType = sortSelect.value;
            if (sortType === 'az') {
                filtered.sort((a, b) => {
                    const tA = lang === 'en' ? (a.title_en || a.title) : a.title;
                    const tB = lang === 'en' ? (b.title_en || b.title) : b.title;
                    return tA.localeCompare(tB);
                });
            } else if (sortType === 'za') {
                filtered.sort((a, b) => {
                    const tA = lang === 'en' ? (a.title_en || a.title) : a.title;
                    const tB = lang === 'en' ? (b.title_en || b.title) : b.title;
                    return tB.localeCompare(tA);
                });
            }
        }
        renderServices(filtered);
    }
}
